services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/expense_db

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    container_name: expense-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: expense-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
